### ISSUE TITLE
Logo mirrored or not?

### ISSUE THREAD

**Issue by VirtualSatai** [f-klubben/FeerPong#7]
The logo on the boards have their logo mirrored relative to (most) other F-Klub logos. 

The suggested plaque (PhysicalDesign/Plack/Version1/Plack.pdf) is identical to the '89 ps file, i.e. mirrored compared with the table. 

Or do they get mirrored in the laser cutting process?

![billede](https://user-images.githubusercontent.com/1919650/38640729-5ec6fd30-3dd5-11e8-8a1b-6632ed707f9e.png)

**Comment by Abstrakten** [comment]
We talked about this matter extensively during the process of designing the logo for the table, and whether to mirror it or not. I do not remember why we came to this conclusion, but the discussion was conducted!

**Comment by hutli** [comment]
Originally it was decided that the integral symbols should be turned correctly despite the original logo being opposite. However, due to massive feedback from our community we have decided that the integral symbols will be in accordance with the original logo in the beta (including the plaque). Thank you for your concern!
